/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
import java.sql.*;
import Conexao.ModuloConexao;
import javax.swing.JOptionPane;
/**
 *
 * @author EU
 */
public class Cadastro_de_Pedido extends javax.swing.JInternalFrame {
    
    public  static boolean clientes;
    public  static boolean estoque;

    
    //Estas variaveis preparam a conexão e exibem os resultados na conexão
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Cadastro_de_Pedido
     */
    public Cadastro_de_Pedido() {
        initComponents();
         //conexão para puxar as informações do banco
        conexao = ModuloConexao.conector();
    }
    
    private void adicionar() {
        String sql = "insert into caprichosa_db.pedidos (modelo, tamanho, medida, quantidade, dt_pedido, dt_entrega, valor, descricao, form_pagamento, fase_atendimeto, resp_atendimento, obs_pedido, clientes_id_cpf_client, funcionarios_id_cpf_func) values  (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
        try {         
            //
             cboCadMod_pedido.setSelectedItem(rs.getString(1));
                cboCadTam_pedidos.setSelectedItem(rs.getString(2));
                textCadMed_Pedido.setText(rs.getString(3));
       //algo de errado jspCadQuant_Pedido.setSelectedItem(rs.getString(4));
                txtCadDt_Entrega.setText(rs.getString(5));
                txtCadDt_Entrega.setText(rs.getString(6));
                txtCadVal_Pedido.setText(rs.getString(7));
                textCadDesc_Pedido.setText(rs.getString(8));
                cboCadPaga_Pedido.setSelectedItem(rs.getString(9));
                cboCadfase_Pedido.setSelectedItem(rs.getString(10));
                cboCadFunc_Pedido.setSelectedItem(rs.getString(11));
       //algo de errado txtClient_Pedido.setText(rs.getString(12));
            //codigo adiona as informações a cima na tabela.
            int adicionado = pst.executeUpdate();
            //
            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso °u°");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        txtCadClient_Pedido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton41 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtCadVal_Pedido = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textCadMed_Pedido = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCod_Cliente = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTel_Cliente = new javax.swing.JFormattedTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton44 = new javax.swing.JButton();
        textCodCad_Pedido1 = new javax.swing.JTextField();
        cboCadMod_pedido = new javax.swing.JComboBox<>();
        cboCadTam_pedidos = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jspCadQuant_Pedido = new javax.swing.JSpinner();
        txtCadDt_Entrega = new javax.swing.JFormattedTextField();
        txtCadDt_pedido1 = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        textCadDesc_Pedido = new javax.swing.JTextField();
        cboCadPaga_Pedido = new javax.swing.JComboBox<>();
        cboCadFunc_Pedido = new javax.swing.JComboBox<>();
        cboCadfase_Pedido = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Pedido");
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1210, 880));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pedido.png"))); // NOI18N
        jLabel2.setText("  Cadastro de Pedido");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 50, 860, 140);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1058, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 1060, 110);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jPanel5.setForeground(new java.awt.Color(0, 204, 255));
        jPanel5.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 204, 255));
        jLabel23.setText("Pedido");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(28, 250, 90, 30);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("Estoque");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(30, 390, 91, 30);

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 204, 255));
        jLabel24.setText("Clientes");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(30, 110, 93, 30);

        jButton45.setBackground(new java.awt.Color(250, 233, 255));
        jButton45.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton45.setForeground(new java.awt.Color(0, 204, 255));
        jButton45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/clientes 64.png"))); // NOI18N
        jButton45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton45);
        jButton45.setBounds(10, 10, 130, 130);

        jButton46.setBackground(new java.awt.Color(250, 233, 255));
        jButton46.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton46.setForeground(new java.awt.Color(0, 204, 255));
        jButton46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/estoque 64.png"))); // NOI18N
        jButton46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton46);
        jButton46.setBounds(10, 290, 130, 130);

        jButton47.setBackground(new java.awt.Color(250, 233, 255));
        jButton47.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton47.setForeground(new java.awt.Color(0, 204, 255));
        jButton47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pedido 64.png"))); // NOI18N
        jButton47.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jPanel5.add(jButton47);
        jButton47.setBounds(10, 150, 130, 130);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(20, 210, 150, 840);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo manasysF.png"))); // NOI18N
        getContentPane().add(jLabel25);
        jLabel25.setBounds(1350, 510, 480, 470);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1521, 407, 0, 0);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Data do Pedido:");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(650, 460, 150, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Data de Entrega:");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(640, 500, 153, 30);
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(1436, 552, 85, 22);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Quantidade:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(1409, 203, 112, 22);

        txtCadClient_Pedido.setForeground(new java.awt.Color(153, 153, 153));
        txtCadClient_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadClient_PedidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCadClient_Pedido);
        txtCadClient_Pedido.setBounds(180, 30, 624, 34);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Nome Completo: ");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 40, 155, 22);

        jButton41.setBackground(new java.awt.Color(250, 233, 255));
        jButton41.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton41.setForeground(new java.awt.Color(0, 204, 255));
        jButton41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cancel-blue.png"))); // NOI18N
        jButton41.setText("Cancelar");
        jButton41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jPanel1.add(jButton41);
        jButton41.setBounds(720, 650, 109, 42);

        jButton43.setBackground(new java.awt.Color(250, 233, 255));
        jButton43.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton43.setForeground(new java.awt.Color(0, 204, 255));
        jButton43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/check blue.png"))); // NOI18N
        jButton43.setText("Concluir");
        jButton43.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton43);
        jButton43.setBounds(840, 650, 107, 41);

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel13.setText("Valor:");

        txtCadVal_Pedido.setForeground(new java.awt.Color(153, 153, 153));
        txtCadVal_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadVal_PedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCadVal_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadVal_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(890, 570, 149, 50);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Modelos: ");
        jLabel21.setToolTipText("");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(350, 180, 86, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Tamanhos:");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(530, 180, 101, 38);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText(" Medidas: ");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 140, 100, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Código Do Pedido: ");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 100, 169, 22);

        textCadMed_Pedido.setForeground(new java.awt.Color(153, 153, 153));
        textCadMed_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCadMed_PedidoActionPerformed(evt);
            }
        });
        jPanel1.add(textCadMed_Pedido);
        textCadMed_Pedido.setBounds(30, 180, 260, 36);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Código Do Cliente: ");
        jLabel22.setToolTipText("");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(380, 100, 171, 22);

        txtCod_Cliente.setForeground(new java.awt.Color(153, 153, 153));
        txtCod_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtCod_Cliente);
        txtCod_Cliente.setBounds(550, 90, 120, 36);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Telefone/ Celular:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(690, 100, 165, 22);

        try {
            txtTel_Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTel_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTel_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtTel_Cliente);
        txtTel_Cliente.setBounds(860, 90, 100, 39);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(830, 580, 100, 100);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Modelo", "Tamanho", "Medida"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 370, 588, 490);

        jPanel7.setBackground(new java.awt.Color(0, 204, 255));

        jButton44.setBackground(new java.awt.Color(250, 233, 255));
        jButton44.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton44.setForeground(new java.awt.Color(0, 204, 255));
        jButton44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/check blue.png"))); // NOI18N
        jButton44.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(956, Short.MAX_VALUE)
                .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 370, 1020, 41);

        textCodCad_Pedido1.setForeground(new java.awt.Color(153, 153, 153));
        textCodCad_Pedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodCad_Pedido1ActionPerformed(evt);
            }
        });
        jPanel1.add(textCodCad_Pedido1);
        textCodCad_Pedido1.setBounds(200, 90, 159, 36);

        cboCadMod_pedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adicionar", "3D", "Anatômica", "Quadrada" }));
        jPanel1.add(cboCadMod_pedido);
        cboCadMod_pedido.setBounds(430, 190, 76, 30);

        cboCadTam_pedidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adicionar", "PP", "P", "M", "G", "GG" }));
        jPanel1.add(cboCadTam_pedidos);
        cboCadTam_pedidos.setBounds(630, 190, 70, 30);

        jLabel26.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel26.setText("Quantidade:");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(730, 190, 103, 23);
        jPanel1.add(jspCadQuant_Pedido);
        jspCadQuant_Pedido.setBounds(830, 190, 70, 30);

        try {
            txtCadDt_Entrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCadDt_Entrega);
        txtCadDt_Entrega.setBounds(800, 500, 120, 30);

        try {
            txtCadDt_pedido1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCadDt_pedido1);
        txtCadDt_pedido1.setBounds(800, 460, 120, 30);

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel17.setText("Descrição:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 230, 92, 23);
        jPanel1.add(textCadDesc_Pedido);
        textCadDesc_Pedido.setBounds(30, 250, 290, 90);

        cboCadPaga_Pedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Forma de pagamento", "PIX", "PiCpAY", "Dinheiro", " " }));
        cboCadPaga_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCadPaga_PedidoActionPerformed(evt);
            }
        });
        jPanel1.add(cboCadPaga_Pedido);
        cboCadPaga_Pedido.setBounds(350, 260, 150, 30);

        cboCadFunc_Pedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reponsável:", "Vitória", "Maiara", "Alessandro" }));
        cboCadFunc_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCadFunc_PedidoActionPerformed(evt);
            }
        });
        jPanel1.add(cboCadFunc_Pedido);
        cboCadFunc_Pedido.setBounds(730, 260, 170, 30);

        cboCadfase_Pedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fase do atendimeto", "Fila de tendimento", "Em Confecção", "Pronto para entrega", "Entregue" }));
        jPanel1.add(cboCadfase_Pedido);
        cboCadfase_Pedido.setBounds(530, 260, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 200, 1040, 840);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo-azul GG.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        //Botão que leva para tela clientes
        Clientes clientes = new Clientes();
        Menu.MenujDesktopPane1.add(clientes);
        clientes.setVisible(true);
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        //Botão que leva para tela de estoque
        Estoque estoque = new Estoque();
        Menu.MenujDesktopPane1.add(estoque);
        estoque.setVisible(true);
    }//GEN-LAST:event_jButton46ActionPerformed

    private void txtCadClient_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadClient_PedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadClient_PedidoActionPerformed

    private void txtCadVal_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadVal_PedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadVal_PedidoActionPerformed

    private void textCadMed_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCadMed_PedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCadMed_PedidoActionPerformed

    private void txtCod_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCod_ClienteActionPerformed

    private void txtTel_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTel_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTel_ClienteActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        //Botão que finaliza um o casdastro de pedido.
        this.dispose();
        Estoque estoque = new Estoque();
        Menu.MenujDesktopPane1.add(estoque);
        estoque.setVisible(true);
    }//GEN-LAST:event_jButton43ActionPerformed

    private void textCodCad_Pedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodCad_Pedido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodCad_Pedido1ActionPerformed

    private void cboCadPaga_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCadPaga_PedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCadPaga_PedidoActionPerformed

    private void cboCadFunc_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCadFunc_PedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCadFunc_PedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCadFunc_Pedido;
    private javax.swing.JComboBox<String> cboCadMod_pedido;
    private javax.swing.JComboBox<String> cboCadPaga_Pedido;
    private javax.swing.JComboBox<String> cboCadTam_pedidos;
    private javax.swing.JComboBox<String> cboCadfase_Pedido;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner jspCadQuant_Pedido;
    private javax.swing.JTextField textCadDesc_Pedido;
    private javax.swing.JTextField textCadMed_Pedido;
    private javax.swing.JTextField textCodCad_Pedido1;
    private javax.swing.JTextField txtCadClient_Pedido;
    private javax.swing.JFormattedTextField txtCadDt_Entrega;
    private javax.swing.JFormattedTextField txtCadDt_pedido1;
    private javax.swing.JTextField txtCadVal_Pedido;
    private javax.swing.JTextField txtCod_Cliente;
    private javax.swing.JFormattedTextField txtTel_Cliente;
    // End of variables declaration//GEN-END:variables
}
