/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author EU
 */
import java.sql.*;
import Conexao.ModuloConexao;
import javax.swing.JOptionPane;

public class Cadastro_de_Cliente extends javax.swing.JInternalFrame {

    public static boolean filapedido;
    public static boolean estoque;

    //Estas variaveis preparam a conexão e exibem os resultados na conexão
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Cadastro_de_Cliente
     */
    public Cadastro_de_Cliente() {
        initComponents();
        //conexão para puxar as informações do banco
        conexao = ModuloConexao.conector();
    }

    //metodo para cadastrar clientes
    private void adicionar() {
        String sql = "insert into caprichosa_db.clientes (id_cpf_client, nome_c, cpf_c, dt_nasc_c, genero_c, contato_c, email_c, cep_c, estado_c,cidade_c,bairro_c, endereco_c, complemento_c, imovel_c,num_casa_c ) values  (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
        try {
            //
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCadId_Cliente.getText());
            pst.setString(2, txtCadNomeCliente.getText());
            pst.setString(3, txtCadCpf_Cliente.getText());
            pst.setString(4, cboCadDia_Cliente.getText());
            pst.setString(5, cboCadSex_Cliente.getSelectedItem().toString());
            pst.setString(6, txtCadTel_Cliente.getText());
            pst.setString(7, txtCadEmail_Cliente.getText());
            pst.setString(8, txtCadCep_Cliente.getText());
            pst.setString(9, cboCadEst_Cliente.getSelectedItem().toString());
            pst.setString(10, txtCadCid_Cliente.getText());
            pst.setString(11, txtCadBair_Cliente.getText());
            pst.setString(12, txtCadEnd_Cliente.getText());
            pst.setString(13, txtCadComp_Cliente.getText());
            pst.setString(14, cboCadResi_Cliente.getSelectedItem().toString());
            pst.setString(15, txtCadN_Res_Cliente.getText());
            //codigo adiona as informações a cima na tabela.
            int adicionado = pst.executeUpdate();
            //
            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso °u°");
                txtCadId_Cliente.setText(null);
                txtCadNomeCliente.setText(null);
                txtCadCpf_Cliente.setText(null);
                cboCadSex_Cliente.setSelectedItem(null);
                txtCadTel_Cliente.setText(null);
                txtCadEmail_Cliente.setText(null);
                txtCadCep_Cliente.setText(null);
                cboCadEst_Cliente.setSelectedItem(null);
                txtCadCid_Cliente.setText(null);
                txtCadBair_Cliente.setText(null);
                txtCadEnd_Cliente.setText(null);
                txtCadComp_Cliente.setText(null);
                cboCadResi_Cliente.setSelectedItem(null);
                txtCadN_Res_Cliente.setText(null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCadNomeCliente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCadBair_Cliente = new javax.swing.JTextField();
        txtCadCid_Cliente = new javax.swing.JTextField();
        txtCadEnd_Cliente = new javax.swing.JTextField();
        txtCadN_Res_Cliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCadComp_Cliente = new javax.swing.JTextArea();
        txtCadCpf_Cliente = new javax.swing.JFormattedTextField();
        txtCadTel_Cliente = new javax.swing.JFormattedTextField();
        txtCadCep_Cliente = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCadEmail_Cliente = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtCadId_Cliente = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboCadDia_Cliente = new javax.swing.JFormattedTextField();
        cboCadSex_Cliente = new javax.swing.JComboBox<>();
        cboCadEst_Cliente = new javax.swing.JComboBox<>();
        cboCadResi_Cliente = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        txtCadCancel_Cliente1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        txtCadConc_Cliente = new javax.swing.JButton();
        txtCadCancel_Cliente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Cliente");
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1210, 880));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pedido.png"))); // NOI18N
        jLabel2.setText("  Cadastro de Cliente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 40, 880, 140);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1048, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 60, 1050, 110);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Nome Completo:");
        jLabel5.setToolTipText("");

        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Contato:");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Endereço:");
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Cep:");
        jLabel9.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Bairro:");
        jLabel11.setToolTipText("");

        txtCadNomeCliente.setForeground(new java.awt.Color(153, 153, 153));
        txtCadNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadNomeClienteActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Residência:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("*Nº:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Cidade:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Estado:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Gênero:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Complementos:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Cpf:");
        jLabel21.setToolTipText("");

        txtCadBair_Cliente.setForeground(new java.awt.Color(153, 153, 153));
        txtCadBair_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadBair_ClienteActionPerformed(evt);
            }
        });

        txtCadCid_Cliente.setForeground(new java.awt.Color(153, 153, 153));
        txtCadCid_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadCid_ClienteActionPerformed(evt);
            }
        });

        txtCadEnd_Cliente.setForeground(new java.awt.Color(153, 153, 153));
        txtCadEnd_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadEnd_ClienteActionPerformed(evt);
            }
        });

        txtCadN_Res_Cliente.setForeground(new java.awt.Color(153, 153, 153));
        txtCadN_Res_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadN_Res_ClienteActionPerformed(evt);
            }
        });

        txtCadComp_Cliente.setColumns(20);
        txtCadComp_Cliente.setRows(5);
        jScrollPane1.setViewportView(txtCadComp_Cliente);

        try {
            txtCadCpf_Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCadTel_Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCadCep_Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadCep_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadCep_ClienteActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Email:");

        txtCadEmail_Cliente.setForeground(new java.awt.Color(153, 153, 153));
        txtCadEmail_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadEmail_ClienteActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 204, 255));

        txtCadId_Cliente.setForeground(new java.awt.Color(153, 153, 153));
        txtCadId_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadId_ClienteActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Codigo do cliente:");
        jLabel22.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCadId_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadId_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel10.setText("Nascimento:");
        jLabel10.setToolTipText("");

        try {
            cboCadDia_Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cboCadSex_Cliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboCadSex_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "masculino", "femenino", "outros" }));
        cboCadSex_Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cboCadSex_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCadSex_ClienteActionPerformed(evt);
            }
        });

        cboCadEst_Cliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboCadEst_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "Su", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cboCadEst_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCadEst_ClienteActionPerformed(evt);
            }
        });

        cboCadResi_Cliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboCadResi_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "casa", "apartamento" }));
        cboCadResi_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCadResi_ClienteActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(0, 204, 255));

        txtCadCancel_Cliente1.setBackground(new java.awt.Color(250, 233, 255));
        txtCadCancel_Cliente1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtCadCancel_Cliente1.setForeground(new java.awt.Color(0, 204, 255));
        txtCadCancel_Cliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/info.png"))); // NOI18N
        txtCadCancel_Cliente1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        txtCadCancel_Cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadCancel_Cliente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(txtCadCancel_Cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCadCancel_Cliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(0, 204, 255));

        txtCadConc_Cliente.setBackground(new java.awt.Color(250, 233, 255));
        txtCadConc_Cliente.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtCadConc_Cliente.setForeground(new java.awt.Color(0, 204, 255));
        txtCadConc_Cliente.setText("+ Cadastrar");
        txtCadConc_Cliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        txtCadConc_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadConc_ClienteActionPerformed(evt);
            }
        });

        txtCadCancel_Cliente.setBackground(new java.awt.Color(250, 233, 255));
        txtCadCancel_Cliente.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtCadCancel_Cliente.setForeground(new java.awt.Color(0, 204, 255));
        txtCadCancel_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cancel-blue.png"))); // NOI18N
        txtCadCancel_Cliente.setText("Cancelar");
        txtCadCancel_Cliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        txtCadCancel_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadCancel_ClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCadConc_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCadCancel_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadConc_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadCancel_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(1, 1, 1)
                                .addComponent(txtCadCep_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadBair_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadCid_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, 0)
                        .addComponent(txtCadNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboCadDia_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboCadSex_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadCpf_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(0, 0, 0)
                                .addComponent(txtCadTel_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadEmail_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(659, 659, 659)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cboCadResi_Cliente, 0, 232, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCadEnd_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCadN_Res_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboCadEst_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(65, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addComponent(txtCadNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboCadDia_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(cboCadSex_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCadTel_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(txtCadCpf_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(txtCadEmail_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cboCadEst_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtCadCid_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtCadCep_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(txtCadBair_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCadEnd_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(txtCadN_Res_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cboCadResi_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(jLabel6)
                .addGap(398, 398, 398)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(190, 240, 1095, 800);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jPanel5.setForeground(new java.awt.Color(0, 204, 255));
        jPanel5.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 255));
        jLabel12.setText("Clientes");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(20, 110, 93, 30);

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 204, 255));
        jLabel20.setText("Estoque");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(30, 390, 91, 30);

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 255));
        jLabel13.setText("Pedido");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(28, 250, 90, 30);

        jButton45.setBackground(new java.awt.Color(250, 233, 255));
        jButton45.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton45.setForeground(new java.awt.Color(0, 204, 255));
        jButton45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/clientes 64.png"))); // NOI18N
        jButton45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton45);
        jButton45.setBounds(10, 10, 130, 130);

        jButton46.setBackground(new java.awt.Color(250, 233, 255));
        jButton46.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton46.setForeground(new java.awt.Color(0, 204, 255));
        jButton46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/estoque 64.png"))); // NOI18N
        jButton46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton46);
        jButton46.setBounds(10, 290, 130, 130);

        jButton47.setBackground(new java.awt.Color(250, 233, 255));
        jButton47.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton47.setForeground(new java.awt.Color(0, 204, 255));
        jButton47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pedido 64.png"))); // NOI18N
        jButton47.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton47);
        jButton47.setBounds(10, 150, 130, 130);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(20, 240, 150, 810);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo manasysF.png"))); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(1350, 510, 480, 470);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo-azul GG.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCadBair_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadBair_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadBair_ClienteActionPerformed

    private void txtCadCid_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadCid_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadCid_ClienteActionPerformed

    private void txtCadEnd_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadEnd_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadEnd_ClienteActionPerformed

    private void txtCadN_Res_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadN_Res_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadN_Res_ClienteActionPerformed

    private void txtCadCep_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadCep_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadCep_ClienteActionPerformed

    private void txtCadCancel_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadCancel_ClienteActionPerformed
        // Cancela operação:
    }//GEN-LAST:event_txtCadCancel_ClienteActionPerformed

    private void txtCadEmail_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadEmail_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadEmail_ClienteActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        //Botão que leva para tela de estoque
        Estoque estoque = new Estoque();
        Menu.MenujDesktopPane1.add(estoque);
        estoque.setVisible(true);
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        //Botão que leva para tela de pedidos
        Fila_de_Pedido filapedido = new Fila_de_Pedido();
        Menu.MenujDesktopPane1.add(filapedido);
        filapedido.setVisible(true);

    }//GEN-LAST:event_jButton47ActionPerformed

    private void txtCadConc_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadConc_ClienteActionPerformed
        // chama o metodo adicionar:
        adicionar();
    }//GEN-LAST:event_txtCadConc_ClienteActionPerformed

    private void txtCadId_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadId_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadId_ClienteActionPerformed

    private void txtCadNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadNomeClienteActionPerformed

    private void cboCadSex_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCadSex_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCadSex_ClienteActionPerformed

    private void cboCadEst_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCadEst_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCadEst_ClienteActionPerformed

    private void cboCadResi_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCadResi_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCadResi_ClienteActionPerformed

    private void txtCadCancel_Cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadCancel_Cliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadCancel_Cliente1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cboCadDia_Cliente;
    private javax.swing.JComboBox<String> cboCadEst_Cliente;
    private javax.swing.JComboBox<String> cboCadResi_Cliente;
    private javax.swing.JComboBox<String> cboCadSex_Cliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCadBair_Cliente;
    private javax.swing.JButton txtCadCancel_Cliente;
    private javax.swing.JButton txtCadCancel_Cliente1;
    private javax.swing.JFormattedTextField txtCadCep_Cliente;
    private javax.swing.JTextField txtCadCid_Cliente;
    private javax.swing.JTextArea txtCadComp_Cliente;
    private javax.swing.JButton txtCadConc_Cliente;
    private javax.swing.JFormattedTextField txtCadCpf_Cliente;
    private javax.swing.JTextField txtCadEmail_Cliente;
    private javax.swing.JTextField txtCadEnd_Cliente;
    private javax.swing.JTextField txtCadId_Cliente;
    private javax.swing.JTextField txtCadN_Res_Cliente;
    private javax.swing.JTextField txtCadNomeCliente;
    private javax.swing.JFormattedTextField txtCadTel_Cliente;
    // End of variables declaration//GEN-END:variables
}
