/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

import java.sql.*;
import Conexao.ModuloConexao;
import javax.swing.JOptionPane;

/**
 *
 * @author EU
 */
public class Cadastro_User extends javax.swing.JInternalFrame {

    public static boolean redefiniruser;

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Cadastro_User
     */
    public Cadastro_User() {
        initComponents();

        //conexão para puxar as informações do banco
        conexao = ModuloConexao.conector();
    }

    //metodo para cadastrar funcionarios
    private void adicionarFunc() {
        String sql = "insert into caprichosa_db.funcionarios (id_cpf_func, nome_f, cpf_f, dt_nasc_f, genero_f, contato_f, email_f, cep_f, estado_f, cidade_f, bairro_f, endereco_f, imovel_f, num_casa_f, complemento_f ) values  (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
        try {
            //
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCadId_Func.getText());
            pst.setString(2, txtNomeCad_Func.getText());
            pst.setString(3, txtCpfCad_Func.getText());
            pst.setString(4, txtNasCad_Func.getText());
            pst.setString(5, cboSexCad_Func.getSelectedItem().toString());
            pst.setString(6, txtTelCad_Func.getText());
            pst.setString(7, txtEmail_Cad_Func.getText());
            pst.setString(8, txtCepCad_Func.getText());
            pst.setString(9, cboEstCad_Func.getSelectedItem().toString());
            pst.setString(10, txtCid_Cad_Func.getText());
            pst.setString(11, txtBairCad_Func.getText());
            pst.setString(12, txtEndCad_Func.getText());
            pst.setString(13, cboResiCad_Func.getSelectedItem().toString());
            pst.setString(14, txtN_Resi_Cad_Func.getText());
            pst.setString(15, txtCompCad_Func.getText());

            //codigo adiciona as informações a cima na tabela.
            int adicionarFunc = pst.executeUpdate();
            //
            if (adicionarFunc > 0) {
                JOptionPane.showMessageDialog(null, "Funcionario cadastrado com sucesso °u°");
                txtNomeCad_Func.setText(null);
                txtNasCad_Func.setText(null);
                txtCpfCad_Func.setText(null);
                cboSexCad_Func.setSelectedItem(null);
                txtTelCad_Func.setText(null);
                txtEmail_Cad_Func.setText(null);
                txtCepCad_Func.setText(null);
                cboEstCad_Func.setSelectedItem(null);
                txtCid_Cad_Func.setText(null);
                txtBairCad_Func.setText(null);
                txtEndCad_Func.setText(null);
                txtCompCad_Func.setText(null);
                cboResiCad_Func.setSelectedItem(null);
                txtN_Resi_Cad_Func.setText(null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //metodo para cadastrar funcionarios
    private void adicionarUser() {
        String sql = "insert into caprichosa_db.login (usuario,senha,cont_senha,tp_user,funcionarios_id_cpf_func) values  (?,?,?,?,?);";
        try {
            //
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCad_user.getText());
            pst.setString(2, passSenhaCad_user.getText());
            pst.setString(3, passCont_SenhaCad_user.getText());
            pst.setString(4, cbo_Tp_User.getSelectedItem().toString());
            pst.setString(5, txtCadId_user_Func.getText());

            //codigo adiciona as informações a cima na tabela.
            int adicionarUser = pst.executeUpdate();
            //
            if (adicionarUser > 0) {
                JOptionPane.showMessageDialog(null, "Funcionario cadastrado com sucesso °u°");
                txtCad_user.setText(null);
                passSenhaCad_user.setText(null);
                passCont_SenhaCad_user.setText(null);
                cbo_Tp_User.setSelectedItem(null);
                txtCadId_user_Func.setText(null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel55 = new javax.swing.JPanel();
        jLabel155 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        txtCadId_Func = new javax.swing.JTextField();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        txtNomeCad_Func = new javax.swing.JTextField();
        txtCpfCad_Func = new javax.swing.JFormattedTextField();
        jLabel157 = new javax.swing.JLabel();
        txtNasCad_Func = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cboSexCad_Func = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtTelCad_Func = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        txtEndCad_Func = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCepCad_Func = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        cboEstCad_Func = new javax.swing.JComboBox<>();
        txtBairCad_Func = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEmail_Cad_Func = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCid_Cad_Func = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cboResiCad_Func = new javax.swing.JComboBox<>();
        txtN_Resi_Cad_Func = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        jLabel159 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        jLabel160 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        txtCadId_user_Func = new javax.swing.JTextField();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        txtCad_user = new javax.swing.JTextField();
        cbo_Tp_User = new javax.swing.JComboBox<>();
        jPanel58 = new javax.swing.JPanel();
        jLabel164 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        passSenhaCad_user = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        passCont_SenhaCad_user = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCompCad_Func = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Usuario");
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1210, 880));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jPanel1.setLayout(null);

        jButton19.setBackground(new java.awt.Color(250, 233, 255));
        jButton19.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 204, 255));
        jButton19.setText("Redefinir");
        jButton19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(970, 10, 100, 30);

        jButton21.setBackground(new java.awt.Color(250, 233, 255));
        jButton21.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton21.setForeground(new java.awt.Color(0, 204, 255));
        jButton21.setText("Cadastro");
        jButton21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(870, 10, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 20, 1080, 50);

        jPanel55.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jPanel55.setLayout(null);

        jLabel155.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel155.setText("Nome completo:");
        jPanel55.add(jLabel155);
        jLabel155.setBounds(20, 110, 132, 23);

        jLabel156.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel156.setText("Id do funcionario:");
        jPanel55.add(jLabel156);
        jLabel156.setBounds(500, 110, 150, 23);
        jPanel55.add(txtCadId_Func);
        txtCadId_Func.setBounds(500, 140, 180, 30);

        jButton51.setBackground(new java.awt.Color(250, 233, 255));
        jButton51.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton51.setForeground(new java.awt.Color(0, 204, 255));
        jButton51.setText("Cancelar");
        jButton51.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jPanel55.add(jButton51);
        jButton51.setBounds(610, 400, 98, 42);

        jButton52.setBackground(new java.awt.Color(250, 233, 255));
        jButton52.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton52.setForeground(new java.awt.Color(0, 204, 255));
        jButton52.setText("Concluir");
        jButton52.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });
        jPanel55.add(jButton52);
        jButton52.setBounds(500, 400, 98, 42);
        jPanel55.add(txtNomeCad_Func);
        txtNomeCad_Func.setBounds(20, 140, 140, 32);

        try {
            txtCpfCad_Func.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel55.add(txtCpfCad_Func);
        txtCpfCad_Func.setBounds(20, 210, 140, 32);

        jLabel157.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel157.setText("Cpf:");
        jPanel55.add(jLabel157);
        jLabel157.setBounds(20, 180, 31, 23);

        try {
            txtNasCad_Func.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel55.add(txtNasCad_Func);
        txtNasCad_Func.setBounds(20, 290, 140, 32);

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 17)); // NOI18N
        jLabel11.setText("Nascimento:");
        jLabel11.setToolTipText("");
        jPanel55.add(jLabel11);
        jLabel11.setBounds(20, 250, 95, 34);

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel18.setText("Gênero:");
        jPanel55.add(jLabel18);
        jLabel18.setBounds(20, 340, 64, 23);

        cboSexCad_Func.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboSexCad_Func.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "masculino", "femenino", "outros" }));
        cboSexCad_Func.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel55.add(cboSexCad_Func);
        cboSexCad_Func.setBounds(20, 370, 112, 28);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel7.setText("Contato:");
        jLabel7.setToolTipText("");
        jPanel55.add(jLabel7);
        jLabel7.setBounds(180, 110, 67, 23);

        try {
            txtTelCad_Func.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel55.add(txtTelCad_Func);
        txtTelCad_Func.setBounds(180, 140, 140, 32);

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel24.setText("Email:");
        jPanel55.add(jLabel24);
        jLabel24.setBounds(180, 180, 50, 23);
        jPanel55.add(txtEndCad_Func);
        txtEndCad_Func.setBounds(340, 290, 140, 32);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel9.setText("Cep:");
        jLabel9.setToolTipText("");
        jPanel55.add(jLabel9);
        jLabel9.setBounds(180, 250, 35, 23);

        try {
            txtCepCad_Func.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel55.add(txtCepCad_Func);
        txtCepCad_Func.setBounds(180, 290, 140, 32);

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel17.setText("Estado:");
        jPanel55.add(jLabel17);
        jLabel17.setBounds(180, 340, 60, 23);

        cboEstCad_Func.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboEstCad_Func.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "Su", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel55.add(cboEstCad_Func);
        cboEstCad_Func.setBounds(180, 370, 100, 28);
        jPanel55.add(txtBairCad_Func);
        txtBairCad_Func.setBounds(340, 210, 140, 32);

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel16.setText("Cidade:");
        jPanel55.add(jLabel16);
        jLabel16.setBounds(340, 110, 60, 23);
        jPanel55.add(txtEmail_Cad_Func);
        txtEmail_Cad_Func.setBounds(180, 210, 140, 32);

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel12.setText(" Bairro:");
        jLabel12.setToolTipText("");
        jPanel55.add(jLabel12);
        jLabel12.setBounds(340, 180, 80, 23);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel8.setText("Endereço:");
        jLabel8.setToolTipText("");
        jPanel55.add(jLabel8);
        jLabel8.setBounds(340, 250, 82, 23);
        jPanel55.add(txtCid_Cad_Func);
        txtCid_Cad_Func.setBounds(340, 140, 140, 32);

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel14.setText("Residência:");
        jPanel55.add(jLabel14);
        jLabel14.setBounds(340, 340, 94, 23);

        cboResiCad_Func.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboResiCad_Func.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "casa", "apartamento" }));
        jPanel55.add(cboResiCad_Func);
        cboResiCad_Func.setBounds(340, 370, 133, 28);
        jPanel55.add(txtN_Resi_Cad_Func);
        txtN_Resi_Cad_Func.setBounds(500, 340, 40, 32);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Nº:");
        jPanel55.add(jLabel15);
        jLabel15.setBounds(460, 340, 31, 22);

        jPanel56.setBackground(new java.awt.Color(51, 204, 255));
        jPanel56.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel159.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabel159.setText("Cadastro de Usuário");

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel56Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jLabel159)
                .addContainerGap())
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel159))
        );

        jPanel55.add(jPanel56);
        jPanel56.setBounds(1, 23, 642, 72);

        jLabel1.setText("Obs. A ID é o CPF sem as pontuações.");
        jPanel55.add(jLabel1);
        jLabel1.setBounds(500, 170, 190, 14);

        jTabbedPane4.addTab("Funcionario", jPanel55);

        jPanel57.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jPanel57.setLayout(null);

        jLabel160.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel160.setText("Usuário:");
        jPanel57.add(jLabel160);
        jLabel160.setBounds(49, 143, 68, 23);

        jLabel162.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel162.setText("Senha:");
        jPanel57.add(jLabel162);
        jLabel162.setBounds(50, 240, 55, 23);

        jLabel163.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel163.setText("Contra senha");
        jPanel57.add(jLabel163);
        jLabel163.setBounds(380, 240, 109, 23);
        jPanel57.add(txtCadId_user_Func);
        txtCadId_user_Func.setBounds(378, 172, 233, 30);

        jButton53.setBackground(new java.awt.Color(250, 233, 255));
        jButton53.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton53.setForeground(new java.awt.Color(0, 204, 255));
        jButton53.setText("Cancelar");
        jButton53.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jPanel57.add(jButton53);
        jButton53.setBounds(570, 380, 98, 42);

        jButton54.setBackground(new java.awt.Color(250, 233, 255));
        jButton54.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton54.setForeground(new java.awt.Color(0, 204, 255));
        jButton54.setText("Concluir");
        jButton54.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        jPanel57.add(jButton54);
        jButton54.setBounds(460, 380, 98, 42);
        jPanel57.add(txtCad_user);
        txtCad_user.setBounds(49, 172, 233, 30);

        cbo_Tp_User.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADM", "COM" }));
        cbo_Tp_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_Tp_UserActionPerformed(evt);
            }
        });
        jPanel57.add(cbo_Tp_User);
        cbo_Tp_User.setBounds(282, 172, 60, 30);

        jPanel58.setBackground(new java.awt.Color(51, 204, 255));
        jPanel58.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel164.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabel164.setText("Cadastro de Usuário");

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel58Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jLabel164)
                .addContainerGap())
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel58Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel164))
        );

        jPanel57.add(jPanel58);
        jPanel58.setBounds(1, 23, 677, 72);

        jLabel158.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel158.setText("Id do funcionario:");
        jPanel57.add(jLabel158);
        jLabel158.setBounds(380, 140, 150, 23);

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Obs. A ID é o CPF sem as pontuações.");
        jPanel57.add(jLabel3);
        jLabel3.setBounds(380, 210, 190, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/eye.png"))); // NOI18N
        jPanel57.add(jLabel4);
        jLabel4.setBounds(240, 280, 20, 16);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel57.add(jCheckBox1);
        jCheckBox1.setBounds(260, 280, 20, 20);

        passSenhaCad_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passSenhaCad_userActionPerformed(evt);
            }
        });
        jPanel57.add(passSenhaCad_user);
        passSenhaCad_user.setBounds(50, 270, 233, 35);

        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Obs.senha direcionado só para ADM.");
        jPanel57.add(jLabel6);
        jLabel6.setBounds(390, 310, 190, 14);

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel57.add(jCheckBox3);
        jCheckBox3.setBounds(590, 280, 20, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/eye.png"))); // NOI18N
        jPanel57.add(jLabel13);
        jLabel13.setBounds(570, 280, 20, 16);

        passCont_SenhaCad_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passCont_SenhaCad_userActionPerformed(evt);
            }
        });
        jPanel57.add(passCont_SenhaCad_user);
        passCont_SenhaCad_user.setBounds(380, 270, 230, 35);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Para cadastrar um usuário primeiro é preciso adicionar um funcionario.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel57.add(jPanel2);
        jPanel2.setBounds(0, 390, 380, 20);

        jTabbedPane4.addTab("Usuário", jPanel57);

        getContentPane().add(jTabbedPane4);
        jTabbedPane4.setBounds(210, 240, 745, 496);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo-azul GG.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1920, 1080);
        getContentPane().add(txtCompCad_Func);
        txtCompCad_Func.setBounds(1330, 500, 7, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton19jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19jButton10ActionPerformed
        // aqui imprime a tela de redefinição de usuário:
        this.dispose();
        Redefinir_User redefiniruser = new Redefinir_User();
        Menu.MenujDesktopPane1.add(redefiniruser);
        redefiniruser.setVisible(true);
    }//GEN-LAST:event_jButton19jButton10ActionPerformed

    private void jButton21jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21jButton12ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        // chama o metodo adicionar:
        adicionarFunc();
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        // chama o metodo adicionar:
        adicionarUser();
    }//GEN-LAST:event_jButton54ActionPerformed

    private void cbo_Tp_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_Tp_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_Tp_UserActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // Mostrar ou ocultar senha ao ser digitada
        if (jCheckBox3.isSelected()) {
            passCont_SenhaCad_user.setEchoChar((char) 0);
        } else {
            passCont_SenhaCad_user.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void passCont_SenhaCad_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passCont_SenhaCad_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passCont_SenhaCad_userActionPerformed

    private void passSenhaCad_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passSenhaCad_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passSenhaCad_userActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // Mostrar ou ocultar senha ao ser digitada
        if (jCheckBox1.isSelected()) {
            passSenhaCad_user.setEchoChar((char) 0);
        } else {
            passSenhaCad_user.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboEstCad_Func;
    private javax.swing.JComboBox<String> cboResiCad_Func;
    private javax.swing.JComboBox<String> cboSexCad_Func;
    private javax.swing.JComboBox<String> cbo_Tp_User;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox58;
    private javax.swing.JComboBox<String> jComboBox59;
    private javax.swing.JComboBox<String> jComboBox60;
    private javax.swing.JComboBox<String> jComboBox61;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField jTextField122;
    private javax.swing.JTextField jTextField123;
    private javax.swing.JTextField jTextField125;
    private javax.swing.JTextField jTextField126;
    private javax.swing.JTextField jTextField127;
    private javax.swing.JTextField jTextField128;
    private javax.swing.JTextField jTextField129;
    private javax.swing.JTextField jTextField130;
    private javax.swing.JPasswordField passCont_SenhaCad_user;
    private javax.swing.JPasswordField passSenhaCad_user;
    private javax.swing.JTextField txtBairCad_Func;
    private javax.swing.JTextField txtCadId_Func;
    private javax.swing.JTextField txtCadId_user_Func;
    private javax.swing.JTextField txtCad_user;
    private javax.swing.JFormattedTextField txtCepCad_Func;
    private javax.swing.JTextField txtCid_Cad_Func;
    private javax.swing.JTextField txtCompCad_Func;
    private javax.swing.JFormattedTextField txtCpfCad_Func;
    private javax.swing.JTextField txtEmail_Cad_Func;
    private javax.swing.JTextField txtEndCad_Func;
    private javax.swing.JTextField txtN_Resi_Cad_Func;
    private javax.swing.JFormattedTextField txtNasCad_Func;
    private javax.swing.JTextField txtNomeCad_Func;
    private javax.swing.JFormattedTextField txtTelCad_Func;
    // End of variables declaration//GEN-END:variables
}
