
import java.sql.*;
import Conexao.ModuloConexao;
import javax.swing.JOptionPane;


/*AXIMIZED_BOTH;
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Aluno
 */
public class Clientes extends javax.swing.JInternalFrame {

    public static boolean filapedido;
    public static boolean estoque;
    public static boolean cliente;
    public static boolean cadastrocliente;

    /**
     * Creates new form Clientes
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Clientes() {
        initComponents();

        //conexão para puxar as informações do banco
        conexao = ModuloConexao.conector();
    }

    private void consultar_cliente() {
        String sql = "select * from clientes where nome_c like ?";
        try {
            pst = conexao.prepareStatement(sql);
            //passando as informações  da pesquisa para ?
            pst.setString(1, txtPes_Cliente.getText() + "%");
            rs = pst.executeQuery();
            // a linha abaixo usa a biblioteca rs2xml.jar para preencher a tabela
           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void info_campos() {
        int setar = jtb_PClientes.getSelectedRow();
        txtNome_Cliente.setText(jtb_PClientes.getModel().getValueAt(setar, 1).toString());
        txtCpf_Cliente.setText(jtb_PClientes.getModel().getValueAt(setar, 2).toString());
        txtNas_Cliente.setText(jtb_PClientes.getModel().getValueAt(setar, 3).toString());
        cboSex_Cliente.setSelectedItem(jtb_PClientes.getModel().getValueAt(setar, 4).toString());
        txtTel_Cliente.setText(jtb_PClientes.getModel().getValueAt(setar, 5).toString());
        txtEmail_Cliente.setText(jtb_PClientes.getModel().getValueAt(setar, 6).toString());
        txtCep_Cliente.setText(jtb_PClientes.getModel().getValueAt(setar, 7).toString());
        cboEst_Cliente.setSelectedItem(jtb_PClientes.getModel().getValueAt(setar, 8).toString());
        txtCid_Cliente.setText(jtb_PClientes.getModel().getValueAt(setar, 9).toString());
        txtBair_Cliente.setText(jtb_PClientes.getModel().getValueAt(setar, 10).toString());
        txtEnd_Cliente.setText(jtb_PClientes.getModel().getValueAt(setar, 11).toString());
        txtComp_Cliente.setText(jtb_PClientes.getModel().getValueAt(setar, 12).toString());
        cboResi_Cliente.setSelectedItem(jtb_PClientes.getModel().getValueAt(setar, 13).toString());
        txtN_Resi_Cliente.setText(jtb_PClientes.getModel().getValueAt(setar, 14).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_PClientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNome_Cliente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtBair_Cliente = new javax.swing.JTextField();
        txtCid_Cliente = new javax.swing.JTextField();
        txtN_Resi_Cliente = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtPes_Cliente = new javax.swing.JTextField();
        cboResi_Cliente = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComp_Cliente = new javax.swing.JTextArea();
        cboEst_Cliente = new javax.swing.JComboBox<>();
        bttNew_Cliente = new javax.swing.JButton();
        txtCep_Cliente = new javax.swing.JFormattedTextField();
        txtEmail_Cliente = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtTel_Cliente = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCpf_Cliente = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        cboSex_Cliente = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtEnd_Cliente = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNas_Cliente = new javax.swing.JFormattedTextField();
        jPanel8 = new javax.swing.JPanel();
        bttRel_Cliente2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        cboResi_Cliente1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Clientes");
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(1920, 990));
        getContentPane().setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo manasysF.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1350, 510, 480, 470);

        jPanel5.setForeground(new java.awt.Color(0, 204, 255));
        jPanel5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("Estoque");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(30, 390, 91, 30);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("Clientes");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(30, 110, 93, 30);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("Pedido");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(28, 250, 90, 30);

        jButton45.setBackground(new java.awt.Color(250, 233, 255));
        jButton45.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton45.setForeground(new java.awt.Color(0, 204, 255));
        jButton45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/clientes 64.png"))); // NOI18N
        jButton45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton45);
        jButton45.setBounds(10, 10, 130, 130);

        jButton46.setBackground(new java.awt.Color(250, 233, 255));
        jButton46.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton46.setForeground(new java.awt.Color(0, 204, 255));
        jButton46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/estoque 64.png"))); // NOI18N
        jButton46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton46);
        jButton46.setBounds(10, 290, 130, 130);

        jButton47.setBackground(new java.awt.Color(250, 233, 255));
        jButton47.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton47.setForeground(new java.awt.Color(0, 204, 255));
        jButton47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pedido 64.png"))); // NOI18N
        jButton47.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton47);
        jButton47.setBounds(10, 150, 130, 130);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(20, 150, 150, 930);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 70)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cliente.png"))); // NOI18N
        jLabel2.setText("Clientes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 0, 410, 167);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 20, 830, 110);

        jtb_PClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código ", "Nome ", "Telefone ", "E-mail", "Cidade "
            }
        ));
        jtb_PClientes.setAlignmentX(2.0F);
        jtb_PClientes.setAlignmentY(2.0F);
        jtb_PClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtb_PClientes.setEditingColumn(2);
        jtb_PClientes.setEditingRow(-10);
        jtb_PClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_PClientesMouseClicked(evt);
            }
        });
        jtb_PClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtb_PClientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_PClientes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 620, 1040, 240);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Nome completo:");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 80, 148, 22);

        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1158, 30, 0, 0);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Cep:");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 242, 41, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("   Bairro:");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(170, 242, 77, 30);

        txtNome_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome_Cliente);
        txtNome_Cliente.setBounds(10, 110, 454, 34);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Residência:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(400, 330, 105, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Nº:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(680, 290, 31, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Cidade:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(510, 250, 68, 22);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Estado:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(780, 250, 67, 22);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Complementos:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(30, 280, 141, 22);

        txtBair_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBair_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtBair_Cliente);
        txtBair_Cliente.setBounds(250, 240, 250, 37);

        txtCid_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCid_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtCid_Cliente);
        txtCid_Cliente.setBounds(590, 240, 179, 37);

        txtN_Resi_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN_Resi_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtN_Resi_Cliente);
        txtN_Resi_Cliente.setBounds(710, 290, 63, 38);

        jPanel6.setBackground(new java.awt.Color(0, 204, 255));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel12.setText("Nome do Cliente:");
        jLabel12.setToolTipText("");

        txtPes_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPes_ClienteActionPerformed(evt);
            }
        });
        txtPes_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPes_ClienteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPes_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPes_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(3, 20, 590, 45);

        cboResi_Cliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboResi_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "casa", "apartamento" }));
        cboResi_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboResi_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(cboResi_Cliente);
        cboResi_Cliente.setBounds(510, 330, 153, 28);

        txtComp_Cliente.setColumns(20);
        txtComp_Cliente.setRows(5);
        jScrollPane2.setViewportView(txtComp_Cliente);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 310, 360, 120);

        cboEst_Cliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboEst_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "Su", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cboEst_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEst_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(cboEst_Cliente);
        cboEst_Cliente.setBounds(850, 250, 174, 28);

        bttNew_Cliente.setBackground(new java.awt.Color(250, 233, 255));
        bttNew_Cliente.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        bttNew_Cliente.setForeground(new java.awt.Color(0, 204, 255));
        bttNew_Cliente.setText("Novo Cliente ");
        bttNew_Cliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        bttNew_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttNew_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(bttNew_Cliente);
        bttNew_Cliente.setBounds(690, 400, 133, 42);

        try {
            txtCep_Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCep_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtCep_Cliente);
        txtCep_Cliente.setBounds(70, 240, 87, 37);

        txtEmail_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail_Cliente);
        txtEmail_Cliente.setBounds(300, 200, 342, 38);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Email:");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(240, 200, 56, 30);

        try {
            txtTel_Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtTel_Cliente);
        txtTel_Cliente.setBounds(100, 200, 125, 39);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Contato:");
        jLabel13.setToolTipText("");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 200, 78, 38);

        try {
            txtCpf_Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCpf_Cliente);
        txtCpf_Cliente.setBounds(530, 160, 111, 39);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Cpf:");
        jLabel21.setToolTipText("");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(490, 160, 37, 40);

        cboSex_Cliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboSex_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "masculino", "feminino", "outros" }));
        cboSex_Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cboSex_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSex_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(cboSex_Cliente);
        cboSex_Cliente.setBounds(350, 160, 112, 28);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Gênero:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(280, 160, 73, 22);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel20.setText("Nascimento:");
        jLabel20.setToolTipText("");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 150, 107, 34);
        jPanel1.add(txtEnd_Cliente);
        txtEnd_Cliente.setBounds(510, 290, 160, 33);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Endereço:");
        jLabel22.setToolTipText("");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(400, 290, 92, 22);

        try {
            txtNas_Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtNas_Cliente);
        txtNas_Cliente.setBounds(120, 160, 125, 39);

        jPanel8.setBackground(new java.awt.Color(0, 204, 255));

        bttRel_Cliente2.setBackground(new java.awt.Color(250, 233, 255));
        bttRel_Cliente2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        bttRel_Cliente2.setForeground(new java.awt.Color(0, 204, 255));
        bttRel_Cliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/updates.png"))); // NOI18N
        bttRel_Cliente2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        bttRel_Cliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRel_Cliente2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(bttRel_Cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(bttRel_Cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(946, 142, 96, 51);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Status:");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(400, 370, 64, 30);

        cboResi_Cliente1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboResi_Cliente1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Ativado", "Desativado" }));
        cboResi_Cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboResi_Cliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(cboResi_Cliente1);
        cboResi_Cliente1.setBounds(470, 370, 130, 28);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(190, 150, 1040, 460);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(190, 860, 1040, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo-azul GG.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1070);

        setBounds(0, 0, 1920, 990);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed

    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        //Botão que leva para tela de estoque
        Estoque estoque = new Estoque();
        Menu.MenujDesktopPane1.add(estoque);
        estoque.setVisible(true);
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        //Botão que leva para tela de pedidos
        Fila_de_Pedido filapedido = new Fila_de_Pedido();
        Menu.MenujDesktopPane1.add(filapedido);
        filapedido.setVisible(true);
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jtb_PClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtb_PClientesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_PClientesKeyReleased

    private void txtNome_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome_ClienteActionPerformed

    private void txtBair_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBair_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBair_ClienteActionPerformed

    private void txtCid_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCid_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCid_ClienteActionPerformed

    private void txtN_Resi_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN_Resi_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN_Resi_ClienteActionPerformed

    private void cboResi_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboResi_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboResi_ClienteActionPerformed

    private void cboEst_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEst_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEst_ClienteActionPerformed

    private void bttNew_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttNew_ClienteActionPerformed
        // botão que leva a tela de cadastro de cliente:
        this.dispose();
        Cadastro_de_Cliente cadastrocliente = new Cadastro_de_Cliente();
        Menu.MenujDesktopPane1.add(cadastrocliente);
        cadastrocliente.setVisible(true);
    }//GEN-LAST:event_bttNew_ClienteActionPerformed

    private void txtCep_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCep_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCep_ClienteActionPerformed

    private void txtEmail_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail_ClienteActionPerformed

    private void cboSex_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSex_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSex_ClienteActionPerformed

    private void bttRel_Cliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRel_Cliente2ActionPerformed
        // chama o metodo alterar:
    }//GEN-LAST:event_bttRel_Cliente2ActionPerformed

    private void jtb_PClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_PClientesMouseClicked
        info_campos();
    }//GEN-LAST:event_jtb_PClientesMouseClicked

    private void txtPes_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPes_ClienteActionPerformed
        // TODO add your handling code here:
        consultar_cliente();
    }//GEN-LAST:event_txtPes_ClienteActionPerformed

    private void txtPes_ClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPes_ClienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPes_ClienteKeyReleased

    private void cboResi_Cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboResi_Cliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboResi_Cliente1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttNew_Cliente;
    private javax.swing.JButton bttRel_Cliente2;
    private javax.swing.JComboBox<String> cboEst_Cliente;
    private javax.swing.JComboBox<String> cboResi_Cliente;
    private javax.swing.JComboBox<String> cboResi_Cliente1;
    private javax.swing.JComboBox<String> cboSex_Cliente;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtb_PClientes;
    private javax.swing.JTextField txtBair_Cliente;
    private javax.swing.JFormattedTextField txtCep_Cliente;
    private javax.swing.JTextField txtCid_Cliente;
    private javax.swing.JTextArea txtComp_Cliente;
    private javax.swing.JFormattedTextField txtCpf_Cliente;
    private javax.swing.JTextField txtEmail_Cliente;
    private javax.swing.JTextField txtEnd_Cliente;
    private javax.swing.JTextField txtN_Resi_Cliente;
    private javax.swing.JFormattedTextField txtNas_Cliente;
    private javax.swing.JTextField txtNome_Cliente;
    private javax.swing.JTextField txtPes_Cliente;
    private javax.swing.JFormattedTextField txtTel_Cliente;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setExtendedState(int MAXIMIZED_BOTH) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
