
import java.sql.*;
import Conexao.ModuloConexao;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author EU
 */
public class Estoque extends javax.swing.JInternalFrame {
    
    public  static boolean clientes;
    public  static boolean filapedido;
    /**
     * Creates new form Estoque
     */
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public Estoque() {
        initComponents();
        //conexão para puxar as informações do banco
        conexao = ModuloConexao.conector();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void consulta_estoque() {
        String sql = "select * from materiaprima where material like ?";
        try {
            pst = conexao.prepareStatement(sql);
            //passando as informações  da pesquisa para ?
            pst.setString(1, txtPes_Estoque.getText() + "%");
            rs = pst.executeQuery();
            // a linha abaixo usa a biblioteca rs2xml.jar para preencher a tabela
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
        //metodo para cadastrar clientes
    private void adicionarMate() {
        String sql = "insert into caprichosa_db.materiaprima(material,tipo,cor,unid_met,obs_mat_prima) values  (?,?,?,?,?);";
        try {
            //
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtMat.getText());
            pst.setString(2, txtTip.getText());
            pst.setString(3, txtCor.getText());
            pst.setString(4, txtQua.getText());
            pst.setString(5, txtMet.getText());
            pst.setString(6, txtObs.getText());
            
            //codigo adiona as informações a cima na tabela.
            int adicionado = pst.executeUpdate();
            //
            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso °u°");
                txtMat.setText(null);
                txtTip.setText(null);
                txtCor.setText(null);
                txtQua.setText(null);
                txtMet.setText(null);
                txtObs.setText(null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_PEstoque = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPes_Estoque = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        txtMat = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtTip = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtQua = new javax.swing.JTextField();
        txtMet = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JEditorPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Estoque de Materiais");
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1210, 880));
        getContentPane().setLayout(null);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jPanel6.setForeground(new java.awt.Color(0, 204, 255));
        jPanel6.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("Clientes");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(30, 110, 93, 30);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("Pedido");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(28, 250, 90, 30);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Estoque");
        jPanel6.add(jLabel1);
        jLabel1.setBounds(30, 390, 91, 30);

        jButton45.setBackground(new java.awt.Color(250, 233, 255));
        jButton45.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton45.setForeground(new java.awt.Color(0, 204, 255));
        jButton45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/clientes 64.png"))); // NOI18N
        jButton45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton45);
        jButton45.setBounds(10, 10, 130, 130);

        jButton46.setBackground(new java.awt.Color(250, 233, 255));
        jButton46.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton46.setForeground(new java.awt.Color(0, 204, 255));
        jButton46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/estoque 64.png"))); // NOI18N
        jButton46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jPanel6.add(jButton46);
        jButton46.setBounds(10, 290, 130, 130);

        jButton47.setBackground(new java.awt.Color(250, 233, 255));
        jButton47.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton47.setForeground(new java.awt.Color(0, 204, 255));
        jButton47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pedido 64.png"))); // NOI18N
        jButton47.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton47);
        jButton47.setBounds(10, 150, 130, 130);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(20, 220, 150, 860);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jPanel3.setLayout(null);

        jtb_PEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Material", "Tipo", "Cor", "Quantidade", "Metragem", "Observação"
            }
        ));
        jScrollPane1.setViewportView(jtb_PEstoque);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(23, 349, 700, 510);

        jButton17.setBackground(new java.awt.Color(250, 233, 255));
        jButton17.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 204, 255));
        jButton17.setText("Excluir");
        jButton17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton17);
        jButton17.setBounds(655, 101, 70, 30);

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel2.setText("Produtos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 123, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(1, 24, 234, 41);

        jPanel5.setBackground(new java.awt.Color(0, 204, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Pesquisar:");
        jLabel4.setToolTipText("");

        txtPes_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPes_EstoqueActionPerformed(evt);
            }
        });
        txtPes_Estoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPes_EstoqueKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(txtPes_Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtPes_Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(1, 83, 461, 48);

        jButton18.setBackground(new java.awt.Color(250, 233, 255));
        jButton18.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 204, 255));
        jButton18.setText("Registrar");
        jButton18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton18);
        jButton18.setBounds(480, 101, 93, 30);

        jButton19.setBackground(new java.awt.Color(250, 233, 255));
        jButton19.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 204, 255));
        jButton19.setText("Editar");
        jButton19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton19);
        jButton19.setBounds(579, 101, 70, 30);

        txtMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatActionPerformed(evt);
            }
        });
        txtMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMatKeyReleased(evt);
            }
        });
        jPanel3.add(txtMat);
        txtMat.setBounds(50, 170, 120, 32);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel21.setText("Material:");
        jLabel21.setToolTipText("");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(50, 150, 110, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel22.setText("Tipo:");
        jLabel22.setToolTipText("");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(180, 150, 110, 20);

        txtTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipActionPerformed(evt);
            }
        });
        txtTip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTipKeyReleased(evt);
            }
        });
        jPanel3.add(txtTip);
        txtTip.setBounds(180, 170, 120, 32);

        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });
        txtCor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorKeyReleased(evt);
            }
        });
        jPanel3.add(txtCor);
        txtCor.setBounds(310, 170, 120, 32);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel23.setText("Cor:");
        jLabel23.setToolTipText("");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(310, 150, 110, 20);

        txtQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuaActionPerformed(evt);
            }
        });
        txtQua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuaKeyReleased(evt);
            }
        });
        jPanel3.add(txtQua);
        txtQua.setBounds(440, 170, 120, 32);

        txtMet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMetActionPerformed(evt);
            }
        });
        txtMet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMetKeyReleased(evt);
            }
        });
        jPanel3.add(txtMet);
        txtMet.setBounds(570, 170, 120, 32);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel24.setText("Observação:");
        jLabel24.setToolTipText("");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(50, 210, 110, 20);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel25.setText("Metragem:");
        jLabel25.setToolTipText("");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(570, 150, 110, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel26.setText("Quantidade:");
        jLabel26.setToolTipText("");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(440, 150, 110, 20);

        jScrollPane3.setViewportView(txtObs);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(50, 230, 250, 90);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(190, 220, 740, 860);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo manasysF.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1350, 510, 480, 470);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/estoque.png"))); // NOI18N
        jLabel8.setText(" Estoque");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 30, 370, 150);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 570, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo-azul GG.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1910, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        //Botão que leva para tela clientes
        Clientes clientes = new Clientes();
        Menu.MenujDesktopPane1.add(clientes);
        clientes.setVisible(true);
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        //Botão que leva para tela de pedidos
        Fila_de_Pedido filapedido = new Fila_de_Pedido();
        Menu.MenujDesktopPane1.add(filapedido);
        filapedido.setVisible(true);
      
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        adicionarMate();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void txtPes_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPes_EstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPes_EstoqueActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void txtPes_EstoqueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPes_EstoqueKeyReleased
        // TODO add your handling code here:
        consulta_estoque();
    }//GEN-LAST:event_txtPes_EstoqueKeyReleased

    private void txtMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatActionPerformed

    private void txtMatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKeyReleased

    private void txtTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipActionPerformed

    private void txtTipKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipKeyReleased

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void txtCorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorKeyReleased

    private void txtQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuaActionPerformed

    private void txtQuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuaKeyReleased

    private void txtMetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMetActionPerformed

    private void txtMetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMetKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMetKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtb_PEstoque;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtMat;
    private javax.swing.JTextField txtMet;
    private javax.swing.JEditorPane txtObs;
    private javax.swing.JTextField txtPes_Estoque;
    private javax.swing.JTextField txtQua;
    private javax.swing.JTextField txtTip;
    // End of variables declaration//GEN-END:variables
}
