/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
import java.sql.*;
import Conexao.ModuloConexao;
import javax.swing.JOptionPane;

/**
 *
 * @author EU
 */
public class Fila_de_Pedido extends javax.swing.JInternalFrame {

    public static boolean clientes;
    public static boolean estoque;
    public static boolean pedido;
    public static boolean cadastropedido;

    /**
     * Creates new form Fila_de_Pedido
     */
    //Estas variaveis preparam a conexão e exibem os resultados na conexão
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Fila_de_Pedido() {
        initComponents();
        //conexão para puxar as informações do banco
        conexao = ModuloConexao.conector();
    }

    private void pesquisa_pedido() {
        String sql = "select * from clientes where nome_c like ?";
        try {
            pst= conexao.prepareStatement(sql);
            //passando as informações  da pesquisa para ?
            pst.setString(1, txt_PPedido.getText() + "%");
            rs=pst.executeQuery();
            // a linha abaixo usa a biblioteca rs2xml.jar para preencher a tabela
           
            
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_Pedidos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNome_Pedido = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jspQuant_Pedido = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        textDesc_Pedido = new javax.swing.JTextField();
        txtTel_Pedido = new javax.swing.JFormattedTextField();
        jButton10 = new javax.swing.JButton();
        cbofase_Pedido = new javax.swing.JComboBox<>();
        cboFunc_Pedido = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtVal_Pedido = new javax.swing.JTextField();
        cboPaga_Pedido = new javax.swing.JComboBox<>();
        cboMod_pedido = new javax.swing.JComboBox<>();
        cboTam_pedidos = new javax.swing.JComboBox<>();
        textMed_Pedido = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtPes_Pedido = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txt_PPedido = new javax.swing.JTextField();
        txtDt_pedido = new javax.swing.JFormattedTextField();
        txtDt_Entrega = new javax.swing.JFormattedTextField();
        jPanel8 = new javax.swing.JPanel();
        bttRel_Cliente2 = new javax.swing.JButton();
        bttRel_Cliente3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Fila de Pedidos");
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1210, 880));
        getContentPane().setLayout(null);

        jtb_Pedidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        jtb_Pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Produto", "Código do Cliente", "Cliente", "Tel.", "Fase de Atendimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb_Pedidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtb_PedidosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtb_Pedidos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(190, 600, 980, 480);

        jPanel5.setForeground(new java.awt.Color(0, 204, 255));
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("Pedido");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(28, 250, 90, 30);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Estoque");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(30, 390, 91, 30);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 255));
        jLabel9.setText("Clientes");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(30, 110, 93, 30);

        jButton45.setBackground(new java.awt.Color(250, 233, 255));
        jButton45.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton45.setForeground(new java.awt.Color(0, 204, 255));
        jButton45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/clientes 64.png"))); // NOI18N
        jButton45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton45);
        jButton45.setBounds(10, 10, 130, 130);

        jButton46.setBackground(new java.awt.Color(250, 233, 255));
        jButton46.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton46.setForeground(new java.awt.Color(0, 204, 255));
        jButton46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/estoque 64.png"))); // NOI18N
        jButton46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton46);
        jButton46.setBounds(10, 290, 130, 130);

        jButton47.setBackground(new java.awt.Color(250, 233, 255));
        jButton47.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton47.setForeground(new java.awt.Color(0, 204, 255));
        jButton47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pedido 64.png"))); // NOI18N
        jButton47.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton47);
        jButton47.setBounds(10, 150, 130, 130);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(20, 170, 150, 930);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo manasysF.png"))); // NOI18N
        getContentPane().add(jLabel30);
        jLabel30.setBounds(1350, 560, 480, 470);

        jLabel32.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/relatorio de pedido.png"))); // NOI18N
        jLabel32.setText("Fila de Pedidos");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(200, 10, 530, 130);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 30, 710, 100);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel8.setToolTipText("");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(13, 503, 0, 0);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel7.setText("Tamanhos:");
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(260, 170, 92, 38);

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel12.setText("Data Do Pedido:");
        jLabel12.setToolTipText("");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(500, 80, 137, 23);

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel10.setText("Nome Completo: ");
        jLabel10.setToolTipText("");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(13, 126, 146, 23);

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel11.setText("Data De Entrega:");
        jLabel11.setToolTipText("");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(740, 80, 147, 23);
        jPanel2.add(txtNome_Pedido);
        txtNome_Pedido.setBounds(159, 120, 512, 34);

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel16.setText(" Medidas: ");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(520, 180, 87, 23);

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel17.setText("Descrição:");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 290, 92, 23);

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel18.setText("Telefone/ Celular: ");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(680, 130, 160, 23);

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel20.setText("Quantidade: ");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(790, 170, 120, 40);
        jPanel2.add(jspQuant_Pedido);
        jspQuant_Pedido.setBounds(900, 170, 70, 30);

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel21.setText("Modelos: ");
        jLabel21.setToolTipText("");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 180, 82, 23);

        jButton7.setBackground(new java.awt.Color(250, 233, 255));
        jButton7.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 204, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/check blue.png"))); // NOI18N
        jButton7.setText("Concluir");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(720, 360, 121, 42);
        jPanel2.add(textDesc_Pedido);
        textDesc_Pedido.setBounds(17, 314, 437, 99);

        try {
            txtTel_Pedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtTel_Pedido);
        txtTel_Pedido.setBounds(844, 119, 129, 36);

        jButton10.setBackground(new java.awt.Color(250, 233, 255));
        jButton10.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 204, 255));
        jButton10.setText("Cadastrar");
        jButton10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton10.setPreferredSize(new java.awt.Dimension(81, 20));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(850, 360, 110, 42);

        cbofase_Pedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fase do atendimento:", "Fila de atendimento", "Em Confecção", "Pronto para entrega", "Entregue" }));
        jPanel2.add(cbofase_Pedido);
        cbofase_Pedido.setBounds(310, 230, 160, 34);

        cboFunc_Pedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reponsável:", "Vitória", "Maiara", "Alessandro" }));
        jPanel2.add(cboFunc_Pedido);
        cboFunc_Pedido.setBounds(160, 230, 140, 34);

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel13.setText("Valor:");

        txtVal_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVal_PedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVal_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVal_Pedido, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel13))
                .addGap(4, 4, 4))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(830, 290, 170, 40);

        cboPaga_Pedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Forma de pagamento:", "PIX", "PiCpAY", "Dinheiro" }));
        cboPaga_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPaga_PedidoActionPerformed(evt);
            }
        });
        jPanel2.add(cboPaga_Pedido);
        cboPaga_Pedido.setBounds(10, 230, 140, 34);

        cboMod_pedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adicionar", "3D", "Anatômica", "Quadrada" }));
        jPanel2.add(cboMod_pedido);
        cboMod_pedido.setBounds(90, 170, 150, 33);

        cboTam_pedidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adicionar", "PP", "P", "M", "G", "GG" }));
        jPanel2.add(cboTam_pedidos);
        cboTam_pedidos.setBounds(360, 170, 150, 33);

        textMed_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMed_PedidoActionPerformed(evt);
            }
        });
        jPanel2.add(textMed_Pedido);
        textMed_Pedido.setBounds(610, 170, 151, 36);

        jPanel7.setBackground(new java.awt.Color(0, 204, 255));

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel14.setText("Código Do Pedido: ");
        jLabel14.setToolTipText("");

        txtPes_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPes_PedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtPes_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPes_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(4, 4, 4))
        );

        jPanel2.add(jPanel7);
        jPanel7.setBounds(3, 64, 438, 44);

        jPanel6.setBackground(new java.awt.Color(0, 204, 255));

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel22.setText("Nome do Cliente: ");
        jLabel22.setToolTipText("");

        txt_PPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PPedidoActionPerformed(evt);
            }
        });
        txt_PPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_PPedidoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_PPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_PPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(4, 4, 4))
        );

        jPanel2.add(jPanel6);
        jPanel6.setBounds(3, 14, 405, 44);

        try {
            txtDt_pedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDt_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDt_pedidoActionPerformed(evt);
            }
        });
        jPanel2.add(txtDt_pedido);
        txtDt_pedido.setBounds(640, 70, 80, 32);

        try {
            txtDt_Entrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtDt_Entrega);
        txtDt_Entrega.setBounds(890, 70, 80, 32);

        jPanel8.setBackground(new java.awt.Color(0, 204, 255));

        bttRel_Cliente2.setBackground(new java.awt.Color(250, 233, 255));
        bttRel_Cliente2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        bttRel_Cliente2.setForeground(new java.awt.Color(0, 204, 255));
        bttRel_Cliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/updates.png"))); // NOI18N
        bttRel_Cliente2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        bttRel_Cliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRel_Cliente2ActionPerformed(evt);
            }
        });

        bttRel_Cliente3.setBackground(new java.awt.Color(250, 233, 255));
        bttRel_Cliente3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        bttRel_Cliente3.setForeground(new java.awt.Color(0, 204, 255));
        bttRel_Cliente3.setText("X");
        bttRel_Cliente3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        bttRel_Cliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRel_Cliente3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(bttRel_Cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttRel_Cliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttRel_Cliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttRel_Cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel8);
        jPanel8.setBounds(830, 10, 150, 59);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(190, 160, 980, 420);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo-azul GG.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        //Botão que leva para tela clientes
        Clientes clientes = new Clientes();
        Menu.MenujDesktopPane1.add(clientes);
        clientes.setVisible(true);
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        //Botão que leva para tela de estoque
        Estoque estoque = new Estoque();
        Menu.MenujDesktopPane1.add(estoque);
        estoque.setVisible(true);
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //Botão que volta pa a fila de pedidos.
        this.dispose();
        Fila_de_Pedido filapedido = new Fila_de_Pedido();
        Menu.MenujDesktopPane1.add(filapedido);
        filapedido.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        //Botão que leva a tela de cadastro de pedido:
        this.dispose();
        Cadastro_de_Pedido cadastropedido = new Cadastro_de_Pedido();
        Menu.MenujDesktopPane1.add(cadastropedido);
        cadastropedido.setVisible(true);

    }//GEN-LAST:event_jButton10ActionPerformed

    private void txtVal_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVal_PedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVal_PedidoActionPerformed

    private void cboPaga_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPaga_PedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPaga_PedidoActionPerformed

    private void textMed_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMed_PedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMed_PedidoActionPerformed

    private void txtPes_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPes_PedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPes_PedidoActionPerformed

    private void txt_PPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PPedidoActionPerformed

    private void txtDt_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDt_pedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDt_pedidoActionPerformed

    private void txt_PPedidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PPedidoKeyReleased
        // O evento abaixa é do tipo em "quando estiver digitando":
        pesquisa_pedido();
    }//GEN-LAST:event_txt_PPedidoKeyReleased

    private void jtb_PedidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtb_PedidosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_PedidosKeyReleased

    private void bttRel_Cliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRel_Cliente2ActionPerformed
        // chama o metodo alterar:
    }//GEN-LAST:event_bttRel_Cliente2ActionPerformed

    private void bttRel_Cliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRel_Cliente3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttRel_Cliente3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttRel_Cliente2;
    private javax.swing.JButton bttRel_Cliente3;
    private javax.swing.JComboBox<String> cboFunc_Pedido;
    private javax.swing.JComboBox<String> cboMod_pedido;
    private javax.swing.JComboBox<String> cboPaga_Pedido;
    private javax.swing.JComboBox<String> cboTam_pedidos;
    private javax.swing.JComboBox<String> cbofase_Pedido;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jspQuant_Pedido;
    private javax.swing.JTable jtb_Pedidos;
    private javax.swing.JTextField textDesc_Pedido;
    private javax.swing.JTextField textMed_Pedido;
    private javax.swing.JFormattedTextField txtDt_Entrega;
    private javax.swing.JFormattedTextField txtDt_pedido;
    private javax.swing.JTextField txtNome_Pedido;
    private javax.swing.JTextField txtPes_Pedido;
    private javax.swing.JFormattedTextField txtTel_Pedido;
    private javax.swing.JTextField txtVal_Pedido;
    private javax.swing.JTextField txt_PPedido;
    // End of variables declaration//GEN-END:variables
}
