/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

import java.sql.*;
import Conexao.ModuloConexao;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class login extends javax.swing.JFrame {
    //Estas variaveis preparam a conexão e exibem os resultados na conexão
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void logar() {
       // realizando a consulta na tabela de login
        String sql = "select * from login where usuario=? and senha=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, Textuser.getText());
            pst.setString(2, Textsenha.getText());
            //execultando a consulta
            rs = pst.executeQuery();
            //se existe usuario e senha correspondente
            if (rs.next()) {

                    Menu dashboard = new Menu();
                    dashboard.setVisible(true);
                    this.dispose();
                
            } else {
                jLabel_mensage.setText("Usuário ou Senha Incorreta");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * Creates new form login'
     */
    public login() {
        initComponents();
        //conexão para puxar as informações do banco
        conexao = ModuloConexao.conector();
        //Indicador de conexão
        if (conexao != null) {
            lblstatus.setText("Conectado");
            lblstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/db_ok.png")));
        } else {
            lblstatus.setText("Desconectado");
            lblstatus.setForeground(Color.red);
            lblstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/db_erro.png")));
        }

        //Centralizando a tela de login
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Entrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Textuser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Textsenha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblstatus = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_up = new javax.swing.JLabel();
        jLabel_mensage = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel7.setText("jLabel7");

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(243, 235, 235));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        Entrar.setBackground(new java.awt.Color(250, 233, 255));
        Entrar.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        Entrar.setForeground(new java.awt.Color(0, 204, 255));
        Entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/login.png"))); // NOI18N
        Entrar.setText("Entrar");
        Entrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        jPanel1.add(Entrar);
        Entrar.setBounds(220, 270, 110, 40);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(69, 69, 69));
        jLabel9.setText("Senha");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 200, 80, 30);

        Textuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextuserActionPerformed(evt);
            }
        });
        jPanel1.add(Textuser);
        Textuser.setBounds(50, 160, 280, 30);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 300, 0, 0);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(69, 69, 69));
        jLabel8.setText("Usuário");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 130, 100, 30);

        Textsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextsenhaActionPerformed(evt);
            }
        });
        jPanel1.add(Textsenha);
        Textsenha.setBounds(50, 230, 280, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/roda pe_PENSI.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 340, 380, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo manasysP.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 0, 130, 140);

        lblstatus.setBackground(new java.awt.Color(165, 163, 163));
        lblstatus.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(0, 204, 255));
        lblstatus.setText("Status de conexão");
        jPanel1.add(lblstatus);
        lblstatus.setBounds(20, 290, 100, 30);

        jCheckBox1.setForeground(new java.awt.Color(69, 69, 69));
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(50, 260, 20, 21);

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        jLabel13.setText("Mostrar senha");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 260, 80, 30);

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(195, 200, 203));
        jLabel14.setText("Sys");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(280, 110, 30, 30);

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(195, 200, 203));
        jLabel12.setText("Mana         ERP");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(250, 110, 120, 30);

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel2.setVerifyInputWhenFocusTarget(false);

        jLabel_up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/up2.png"))); // NOI18N
        jLabel_up.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_upMouseClicked(evt);
            }
        });

        jLabel_mensage.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jLabel_mensage.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_mensage.setText("Error. 473");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_mensage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(jLabel_up, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_mensage)
                    .addComponent(jLabel_up, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 320, 380, 0);

        jLabel16.setBackground(new java.awt.Color(165, 163, 163));
        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(139, 142, 145));
        jLabel16.setText("Esqueceu sua senha ??");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16);
        jLabel16.setBounds(120, 330, 130, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        setBounds(0, 0, 395, 467);
    }// </editor-fold>//GEN-END:initComponents
        //mostar ou ocultar mensagem de erro
    Timer vaisubir = new Timer(20, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (jPanel2.getHeight() != -30) {
                jPanel2.setBounds(jPanel2.getX(), jPanel2.getY(), jPanel2.getWidth(), jPanel2.getHeight() - 5);
            } else {
                vaisubir.stop();
            }
        }
    });

    Timer vaidescer = new Timer(20, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (jPanel2.getHeight() != 30) {
                jPanel2.setBounds(jPanel2.getX(), jPanel2.getY(), jPanel2.getWidth(), jPanel2.getHeight() + 5);
            } else {
                vaidescer.stop();
            }
        }
    });


    private void TextsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextsenhaActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // Mostrar ou ocultar senha ao ser digitada
        if (jCheckBox1.isSelected()) {
            Textsenha.setEchoChar((char) 0);
        } else {
            Textsenha.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void TextuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextuserActionPerformed
        // TODO add your handling code here:...
    }//GEN-LAST:event_TextuserActionPerformed

    private void jLabel_upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_upMouseClicked
        // Ao clicar no icone irá ocultar a notificação
        vaisubir.start();
    }//GEN-LAST:event_jLabel_upMouseClicked

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        //get values
        logar();

        String username = Textuser.getText().trim();
        String password = String.valueOf(Textsenha.getPassword()).trim();

        // if the username is empty
        if (username.equals("")) {
            jLabel_mensage.setText("Entre com seu usuário primeiro");
        } else if (password.equals("")) {
            jLabel_mensage.setText("Está faltando inserir sua senha");
        }

        // Ao clicar irá confirmar o acesso ou negar acesso e notificar
        vaidescer.start();
    }//GEN-LAST:event_EntrarActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // Aqui imprime a tela de suporte ao usuário:
        Suporte obj = new Suporte();
        obj.setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JPasswordField Textsenha;
    private javax.swing.JTextField Textuser;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_mensage;
    private javax.swing.JLabel jLabel_up;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblstatus;
    // End of variables declaration//GEN-END:variables
}
