/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dbmuser
 */
public class Menu extends javax.swing.JFrame {

    public static boolean clientes;
    public static boolean filapedidos;
    public static boolean estoque;
    public static boolean propriedades;
    
    private Pedido objPedido;
    
    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
        //Centralizando a tela de login
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        MenujDesktopPane1 = new javax.swing.JDesktopPane();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setPreferredSize(new java.awt.Dimension(1366, 768));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");
        setMinimumSize(new java.awt.Dimension(1145, 735));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton9.setFont(new java.awt.Font("Bahnschrift", 1, 60)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cliente.png"))); // NOI18N
        jButton9.setText("Clientes");
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        MenujDesktopPane1.add(jButton9);
        jButton9.setBounds(0, 160, 760, 170);

        jButton7.setFont(new java.awt.Font("Bahnschrift", 1, 60)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pedido.png"))); // NOI18N
        jButton7.setText("Pedidos");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        MenujDesktopPane1.add(jButton7);
        jButton7.setBounds(0, 370, 940, 170);

        jButton8.setFont(new java.awt.Font("Bahnschrift", 1, 60)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/estoque.png"))); // NOI18N
        jButton8.setText("Estoque");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        MenujDesktopPane1.add(jButton8);
        jButton8.setBounds(0, 590, 1130, 170);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logotopo.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        MenujDesktopPane1.add(jLabel4);
        jLabel4.setBounds(1020, 70, 169, 171);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo manasysF.png"))); // NOI18N
        MenujDesktopPane1.add(jLabel5);
        jLabel5.setBounds(1350, 510, 480, 470);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel1.setBackground(new java.awt.Color(103, 91, 249));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 80)); // NOI18N
        jLabel1.setText("Menu");
        jPanel2.add(jLabel1);

        MenujDesktopPane1.add(jPanel2);
        jPanel2.setBounds(30, 0, 220, 1040);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo-azul GG.jpg"))); // NOI18N
        MenujDesktopPane1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1920, 1060);

        getContentPane().add(MenujDesktopPane1);
        MenujDesktopPane1.setBounds(-1, 0, 1920, 990);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Maximizando a tela:
        setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //botão leva ao modulo de clientes
        if (clientes == false) {
            Clientes obj = new Clientes();
            MenujDesktopPane1.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //botão leva ao modulo de pedido
        if (filapedidos == false) {
            Fila_de_Pedido obj = new Fila_de_Pedido();
            MenujDesktopPane1.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       //botão leva ao modulo de estoque
        if (estoque == false) {
            Estoque obj = new Estoque();
            MenujDesktopPane1.add(obj);
            obj.setVisible(true);
       }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // aqui imprime a tela de propriedades:
        if (propriedades == false) {
            Propriedades obj = new Propriedades();
            MenujDesktopPane1.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane MenujDesktopPane1;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

   
}
